/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'home' at '2/8/19 8:12 PM' with Gradle 2.14.1
 *
 * @author home, @date 2/8/19 8:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
